---
- hosts: all
  user: root
  tasks:
    - name: Install basics packages
      apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=3600
      with_items:
      - python-virtualenv
      - build-essential
      - libpq-dev
      - git
      - python-dev
      - python-apt
      - python-httplib2
      tags: packages
    - name: Add new user to system
      user: name=app state=present
